force-app/main/default/objects/Account/fields/Quickbook_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>Quickbook_Customer_Id__c</fullName>
    <externalId>true</externalId>
    <label>Quickbook Customer Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quickbook_Invoice__c/Quickbook_Invoice__c.object-meta.xml
<CustomObject>
    <label>Quickbook Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quickbook Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quickbook_Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>InvoiceAccounts</relationshipLabel>
    <relationshipName>Invoice_Account</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quickbook_Invoice__c/fields/Balance_Due__c.field-meta.xml
<CustomField>
    <fullName>Balance_Due__c</fullName>
    <label>Balance Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quickbook_Invoice__c/fields/Quickbook_Invoice_Id__c.field-meta.xml
<CustomField>
    <fullName>Quickbook_Invoice_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Quickbook Invoice Id</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Quickbook_Invoice__c/fields/Quickbook_Invoice_Link__c.field-meta.xml
<CustomField>
    <fullName>Quickbook_Invoice_Link__c</fullName>
    <formula>HYPERLINK(&quot;https://app.qbo.intuit.com/app/invoice?txnId=&quot; + Quickbook_Invoice_Id__c, &quot;View&quot;, &quot;_blank&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quickbook Invoice Link</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quickbook_Invoice__c/fields/Quickbook_Status_Backend__c.field-meta.xml
<CustomField>
    <fullName>Quickbook_Status_Backend__c</fullName>
    <label>Quickbook Status (Backend)</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quickbook_Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF( Balance_Due__c = 0 , 
	&apos;Paid&apos;,  
	IF( Balance_Due__c &lt; Total_Amount__c , 
		&apos;Partially Paid&apos;, 
		&apos;Unpaid&apos;
	)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Batch_createAllSFInvoicesOnQuickBook.cls
/**
*  Purpose         : This class is scheduled whenever we need to send SF Invoives data to QuickBook online account 
*                    It will create Invoice record same as exist in SF org
*
*  Created Date    : 27/09/2023
*
*  Created By      : Rajveer Singh Rawat
*
*  Revision Logs   : V1.0 - Created
*
**/
global with sharing class Batch_createAllSFInvoicesOnQuickBook implements Database.Batchable<sObject>,Database.AllowsCallouts{
   
   //Fetch all the SF org Invoices record 
   public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([SELECT Id, IsDeleted, Name, CurrencyIsoCode, CreatedDate, CreatedById, LastModifiedDate, LastModifiedById, SystemModstamp, 
                                         LastActivityDate, LastViewedDate, LastReferencedDate, Account__c, Balance_Due__c, Due_Date__c, Invoice_Date__c, Quickbook_Invoice_Id__c, 
                                         Quickbook_Status_Backend__c, Sub_Total__c, Tax__c, Account__r.Quickbook_Customer_Id__c, Total_Amount__c, Quickbook_Invoice_Link__c, Status__c 
                                         From Quickbook_Invoice__c Where Id != null WITH SECURITY_ENFORCED]);
    }
    
    public void execute(Database.BatchableContext bc, List<Quickbook_Invoice__c> quickBookInvoices){
        //Call this method to create QuickBook invoices records on QuickBook online account
        QuickbookService.createQuickBookInvoices(quickBookInvoices); 
    }
    
    //Execute any post-processing operations
    public void finish(Database.BatchableContext bc){}
}