force-app/main/default/objects/Account/fields/Quickbook_Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>Quickbook_Customer_Id__c</fullName>
    <externalId>true</externalId>
    <label>Quickbook Customer Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quickbook_Connection__c/Quickbook_Connection__c.object-meta.xml
<CustomObject>
    <label>Quickbook Connection</label>
    <nameField>
        <label>Quickbook Connection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quickbook Connections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quickbook_Connection__c/fields/Access_Token__c.field-meta.xml
<CustomField>
    <fullName>Access_Token__c</fullName>
    <label>Access Token</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quickbook_Connection__c/fields/Access_Token_Expires_In__c.field-meta.xml
<CustomField>
    <fullName>Access_Token_Expires_In__c</fullName>
    <label>Access Token Expires In</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quickbook_Connection__c/fields/Company_Id__c.field-meta.xml
<CustomField>
    <fullName>Company_Id__c</fullName>
    <label>Company Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quickbook_Connection__c/fields/Token_Updated_At__c.field-meta.xml
<CustomField>
    <fullName>Token_Updated_At__c</fullName>
    <label>Token Updated At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Quickbook_Invoice__c/Quickbook_Invoice__c.object-meta.xml
<CustomObject>
    <label>Quickbook Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quickbook Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quickbook_Invoice__c/fields/Balance_Due__c.field-meta.xml
<CustomField>
    <fullName>Balance_Due__c</fullName>
    <label>Balance Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quickbook_Invoice__c/fields/Quickbook_Invoice_Id__c.field-meta.xml
<CustomField>
    <fullName>Quickbook_Invoice_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Quickbook Invoice Id</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Quickbook_Service_Line__c/Quickbook_Service_Line__c.object-meta.xml
<CustomObject>
    <label>Quickbook Service Line</label>
    <nameField>
        <label>Service Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quickbook Service Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quickbook_Service_Line__c/fields/Quickbook_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Quickbook_Invoice__c</fullName>
    <label>Quickbook Invoice</label>
    <referenceTo>Quickbook_Invoice__c</referenceTo>
    <relationshipLabel>Quickbook Invoices</relationshipLabel>
    <relationshipName>Quickbook_Invoices1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quickbook_Service_Line__c/fields/Quickbook_Invoice_Id__c.field-meta.xml
<CustomField>
    <fullName>Quickbook_Invoice_Id__c</fullName>
    <externalId>true</externalId>
    <label>Quickbook Invoice Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuickbookSetting__c/QuickbookSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom settings info for quickbook connection application</description>
    <label>QuickbookSetting</label>
</CustomObject>

force-app/main/default/objects/QuickbookSetting__c/fields/CDCBatchFrequencyINHours__c.field-meta.xml
<CustomField>
    <fullName>CDCBatchFrequencyINHours__c</fullName>
    <description>This field will store the data in hours to fetch CDC data less than this field value to current date.</description>
    <inlineHelpText>Enter data in hours.</inlineHelpText>
    <label>CDCBatchFrequencyINHours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuickbookSetting__c/fields/ClientId__c.field-meta.xml
<CustomField>
    <fullName>ClientId__c</fullName>
    <label>ClientId</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuickbookSetting__c/fields/ClientSecret__c.field-meta.xml
<CustomField>
    <fullName>ClientSecret__c</fullName>
    <label>ClientSecret</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuickbookSetting__c/fields/QBToSFCallout__c.field-meta.xml
<CustomField>
    <fullName>QBToSFCallout__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to able or disable callout from between Quickbook online to salesforce org.</description>
    <label>QBToSFCallout</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuickbookSetting__c/fields/SFToQBCallout__c.field-meta.xml
<CustomField>
    <fullName>SFToQBCallout__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to able or disable callout from between salesforce org to Quickbook online.</description>
    <label>SFToQBCallout</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Batch_getAllQuickBookInvoicesTest.cls
/**
*  Purpose         : This class is the test class for Batch_getAllQuickBookInvoices
*
*  Created Date    : 25/09/2023
*
*  Created By      : Rajveer Singh Rawat
*
*  Revision Logs   : V1.0 - Created
*
**/
@isTest
public class Batch_getAllQuickBookInvoicesTest {
    
    //This method will get the invoice data from Quickbook online and insert record here
    @isTest
    public static void test_getInvoices() {
        
        //setup data 
        mockData();
         //Query Account records
        List<Account> accountlist = [Select Name,Quickbook_Customer_Id__c From Account Where Name = 'FEXLE Services Private Limited' Order By Quickbook_Customer_Id__c];
        
        //QuickBook Custom setting 
        QuickbookSetting__c qbSetting = getQBSetting();
        //QuickBook connection 
        Quickbook_Connection__c connection = getQBConnection();
        QuickbookHttpMockResponse.CALLOUT_TYPE = 'QB-invoice-No-SerLine-callout';
        Test.setMock(HttpCalloutMock.class, new QuickbookHttpMockResponse());
        
        Test.StartTest();          
        //Execute batch
        Database.executeBatch(new Batch_getAllQuickBookInvoices(1,null));
        Test.stopTest();
        
        //Inserted records
        //QB Invoice records
        List<Quickbook_Invoice__c> invoiceRecs = [Select id, Name, Total_Amount__c, Balance_Due__c from Quickbook_Invoice__c];
        //Service Lines
        List<Quickbook_Service_Line__c> serviceLines = [Select id,Quickbook_Invoice_Id__c,Quickbook_Invoice__c,Name From Quickbook_Service_Line__c];
        System.assertEquals(invoiceRecs.size(), 1);
        System.assertEquals(invoiceRecs[0].Name, 'IN-1075');
        System.assertEquals(serviceLines.size(), 1);
        System.assertEquals(serviceLines[0].Quickbook_Invoice__c, invoiceRecs[0].Id);
    }
    
    //This method will test the Invoice record with no service lines
    @isTest
    public static void test_getInvoicesNoLines() {
        
        //QuickBook Custom setting 
        QuickbookSetting__c qbSetting = getQBSetting();
        //QuickBook connection 
        Quickbook_Connection__c connection = getQBConnection();
        
        Test.startTest();
        //Execute batch
        QuickbookHttpMockResponse.CALLOUT_TYPE = 'No-invoice-Lines';
        Test.setMock(HttpCalloutMock.class, new QuickbookHttpMockResponse());
        
        // Start the batch job
        try{
            Batch_getAllQuickBookInvoices batchInstance = new Batch_getAllQuickBookInvoices(1,null);
            Id batchJobId = Database.executeBatch(batchInstance);
            Test.stopTest();
        }catch(Exception e){
            System.assertEquals(e.getMessage(), 'Required lines data not found.');
        }
    }
    
    //This method will test the Invoice record with no customer references 
    @isTest
    public static void test_NoCustomerRef() {
        
        //setup data 
        mockData();
        
        //QuickBook Custom setting 
        QuickbookSetting__c qbSetting = getQBSetting();
        //QuickBook connection 
        Quickbook_Connection__c connection = getQBConnection();
        QuickbookHttpMockResponse.CALLOUT_TYPE = 'NoCustomer-invoice-callout';
        Test.setMock(HttpCalloutMock.class, new QuickbookHttpMockResponse());
        
        Try{
            Test.StartTest();  
            //Execute batch
            Database.executeBatch(new Batch_getAllQuickBookInvoices(1,null));
            Test.stopTest();
        }Catch(Exception e){
            System.assertEquals(e.getMessage(), 'Required SF account with Quickbook customer id');
        } 
    }
    
    //This method will test the Invoice record have improper descriptions
    @isTest
    public static void test_improperDescription() {
        
        //setup data 
        mockData();
        
        //QuickBook Custom setting 
        QuickbookSetting__c qbSetting = getQBSetting();
        //QuickBook connection 
        Quickbook_Connection__c connection = getQBConnection();

        QuickbookHttpMockResponse.CALLOUT_TYPE = 'QB-ImpDescription-invoice-callout';
        Test.setMock(HttpCalloutMock.class, new QuickbookHttpMockResponse());
        
        Test.StartTest();  
        //Execute batch
        Database.executeBatch(new Batch_getAllQuickBookInvoices(1,null));
        Test.stopTest();
        
        //Inserted records
        //QB Invoice records
        List<Quickbook_Invoice__c> invoiceRecs = [Select id, Name, Total_Amount__c,Sub_Total__c,Balance_Due__c from Quickbook_Invoice__c];
        
        //Service Lines
        List<Quickbook_Service_Line__c> serviceLines = [Select id,Quickbook_Invoice_Id__c,Quickbook_Invoice__c,Name From Quickbook_Service_Line__c];
        System.assertEquals(invoiceRecs.size(), 1);
        System.assertEquals(invoiceRecs[0].Name, 'IN-1075');
        System.assertEquals(invoiceRecs[0].Sub_Total__c, 4500);
        System.assertEquals(serviceLines.size(), 0);
    }
    
    //This method will test the Invoice record have no descriptions
    @isTest
    public static void test_NoDescription() {
        
        //setup data 
        mockData();
        
        //QuickBook Custom setting 
        QuickbookSetting__c qbSetting = getQBSetting();
        //QuickBook connection 
        Quickbook_Connection__c connection = getQBConnection();
        QuickbookHttpMockResponse.CALLOUT_TYPE = 'No-Desc-invoice-callout';
        Test.setMock(HttpCalloutMock.class, new QuickbookHttpMockResponse());
        
        Try{
            Test.StartTest();  
            //Execute batch
            Database.executeBatch(new Batch_getAllQuickBookInvoices(1,null));
            Test.stopTest();
        }Catch(Exception e){
            System.assert(e.getMessage().contains('Line description not available for invoice record'));
        } 
    }
    
    //Get QB connection record 
    public static Quickbook_Connection__c getQBConnection(){
        Quickbook_Connection__c connection = new Quickbook_Connection__c();
        connection.Company_Id__c = 'CompanyId';
        connection.Access_Token__c = 'accesstoken';
        connection.Refresh_Token__c = 'refreshtoken';
        connection.Token_Updated_At__c = DateTime.now();
        connection.Access_Token_Expires_In__c = 3600;
        connection.Refresh_Token_Expires_In__c = 180000;
        connection.Name = QuickbookConstants.CONNECTION_NAME;
        insert connection;
        return connection;
    }
    
    //Get QuickBook custom setting record
    public static QuickbookSetting__c getQBSetting(){
        //Test when custom setting is present 
        QuickbookSetting__c setting = new QuickbookSetting__c();
        setting.ClientId__c = 'clientId';
        setting.ClientSecret__c = 'secret';
        setting.CDCBatchFrequencyINHours__c = 2;
        setting.SFToQBCallout__c = true;
        setting.QBToSFCallout__c = true;
        insert setting;
        return setting;
    }
    
    //Create all setup records
    public static void mockData() {
        //Create account records
        List<Account> listOfAccounts = new List<Account>();
        listOfAccounts.add(new Account(Name='FEXLE Services Private Limited',Active__c='true',Quickbook_Customer_Id__c='59'));
        listOfAccounts.add(new Account(Name='FEXLE Services Private Limited',Active__c='true',Quickbook_Customer_Id__c='2'));
        insert listOfAccounts;
    }
}